### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/keto-k8#35]
### e2e tests

We simply need to run the kmm cli with the master option and verify the process gets to the end AND the API is up (at a minimum).

### Complexities

Fundamentally our solution is built around CoreOS as we are currently using the CoreOS kubelet-wrapper to include normal OS dependencies.

If we want to fail ultra quick we would like to run the e2e test with docker only but to achieve this we would have to tackle the question below.

The choice is therefore:
1.  Create a drone compatible e2e test (see below)
2. Create an AWS instance (will work and be quick to implement) as the kubelet will want to start containers

### Questions to answer for option 1.

Investigate issues / services that are required for this to work in drone:

- [x] One of:
    - Update kmm to NOT use the `kubelet-wrapper`
    - Write a kubelet-wrapper script replacement that doesn't depend on rkt - it is just a shell script we could fix-up for drone...
- [x] Test systemd in docker -see: https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/
- [x] Would our (`kubeadm`) manifests and hyperkube images work on a drone node?
- [x] Run with no cloud-provider - updates to keto-tokens

**Comment by vaijab** [comment]
I'd say run coreos in a container with systemd.

**Comment by lewismarshall** [comment]
Thanks for that. More information or actual information please...!

**Comment by lewismarshall** [comment]
`Kubeadm` work on this: https://github.com/kubernetes/kubeadm/issues/17 - should probably use same base image.

**Comment by vaijab** [comment]
> More information or actual information please

https://github.com/UKHomeOffice/docker-systemd

**Comment by lewismarshall** [comment]
Fied by #56
